### ISSUE TITLE
SVG tag <use> doesn't work within polymer component in FireFox

### ISSUE THREAD

**Issue by miriti** [Polymer/polymer#1182]
Here is an example: http://miriti.ru/svgtest/
If you'll look at this example in any browser you will see two grey squares with green circles (labled "Symbol") inside. Except for Firefox (I'm testing on Firefox 35.0.1 on windows and mac os x). 
These SVGs are absolutely identical but the second one is placed inside the polymer component.

Here is the code of the index.html:

``` html
<!doctype html>
<html>
<head>
    <title>Polymer SVG "use" test</title>
    <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
    <link href="bower_components/polymer/polymer.html">
    <link rel="import" href="svg-component.html">
</head>
<body>
<table>
    <tr>
        <td>
            <svg width="400" viewBox="0 0 400 400">
                <defs>
                    <symbol id="usingSymbol" viewBox="-25 -25 50 50">
                        <circle r="25" fill="#afa"></circle>
                        <text x="-25" y="5">
                            Symbol
                        </text>
                    </symbol>
                </defs>

                <rect width="400" height="400" fill="#ccc"></rect>

                <use xlink:href="#usingSymbol" x="100" y="100" width="100"></use>
            </svg>
        </td>
        <td>
            <svg-component></svg-component>
        </td>
    </tr>
</table>
</body>
</html>
```

svg-component.html:

```
<link rel="import" href="bower_components/polymer/polymer.html">

<polymer-element name="svg-component">
    <template>
        <svg width="400" viewBox="0 0 400 400">
            <defs>
                <symbol id="usingSymbol" viewBox="-25 -25 50 50">
                    <circle r="25" fill="#afa"></circle>
                    <text x="-25" y="5">
                        Symbol
                    </text>
                </symbol>
            </defs>

            <rect width="400" height="400" fill="#ccc"></rect>

            <use xlink:href="#usingSymbol" x="100" y="100" width="100"></use>
        </svg>
    </template>
    <script>
        Polymer({});
    </script>
</polymer-element>
```

Code on GitHub: https://github.com/miriti/svgtest

Any suggestion about what can be the cause of this problem?

**Comment by miriti** [comment]
Someone on stackoverflow found a workaround to get this example work in Firefox: http://stackoverflow.com/a/28477601/1593189 here is a fixed example: http://miriti.ru/svgtest-fixed/
But I still think that it shouldn't be like that...

**Comment by miriti** [comment]
Any thoughts about this one?

**Comment by longsonr** [comment]
webcomponents.js does not seem to have any setAttributeNS calls. setting an xlink:href attribute needs to be done via setAttributeNS and not setAttribute.

**Comment by miriti** [comment]
Why it sets any attributes in the first place? Shouldn't it just copy the tree as is?

**Comment by atdotslashdot** [comment]
the same problem occurs in for iron-iconset-svg (1.0.4)
 the 'use' elements don't get rendered

**Comment by jogibear9988** [comment]
I've the same problem with Polymer 1.0 using this Image: http://images.google.de/imgres?imgurl=https://upload.wikimedia.org/wikipedia/commons/1/12/Right_arrow.svg&imgrefurl=https://commons.wikimedia.org/wiki/File:Right_arrow.svg&h=364&w=434&tbnid=d7Q2shW4gEPV_M:&tbnh=91&tbnw=109&docid=z57RoEVcDFZWNM&usg=__8G1qN2S4W_hp1CGUnfW1wgJmBK4=&sa=X&ved=0ahUKEwjglJLukaTKAhVHSRoKHYHOBgYQ9QEIHjAA in a component! Any News?

**Comment by jogibear9988** [comment]
also not working in polymer 2.0

**Comment by phun-ky** [comment]
There is surprisingly  low traction on this issue. What is the status of this?

**Comment by longsonr** [comment]
Firefox has updated to implement this part of the SVG 2 specification so the code here should work now. I imagine nobody cares that it is broken in old Firefox versions (and possibly Safari).

**Comment by phun-ky** [comment]
@longsonr I use the latest firefox (54) and this issue is still valid.

**Comment by longsonr** [comment]
maybe you need to change your source from xlink:href to href. Hard to say really as the testcase has disappeared.

**Comment by jogibear9988** [comment]
if you don't use the namespace how should it work???

**Comment by longsonr** [comment]
What is unclear about what I wrote?

**Comment by mmicuteksystems** [comment]
With 56 it should be fine.
