### ISSUE TITLE
CSS over specificity when using vars 

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2531]
```html
<dom-module id="x-foo">
  <template>
     :host {
        background: var(--foo, red);
     }
    :host(.zap) {
        background: orange;
     }
  </template>
  <content></content>
</dom-module>
```

```html
<x-foo>i am red</x-foo>
<x-foo class='zap'>i am red also?!</x-foo>
```

------

Discovered here:
https://github.com/PolymerElements/paper-toolbar/pull/40/files

**Comment by samccone** [comment]
xref: https://github.com/Polymer/polymer/issues/2439#issuecomment-145927714

**Comment by ebidel** [comment]
Here's a working bin: http://jsbin.com/suhaqezoqa/edit?html,output

**Comment by samccone** [comment]
thanks @ebidel +100

**Comment by abdonrd** [comment]
Your jsbin, @ebidel, is not working for me. :/

**Comment by ebidel** [comment]
It shouldn't work, right? It shows reproducing the bug.

**Comment by abdonrd** [comment]
Aah, okey! Sorry @ebidel! :sweat_smile:

**Comment by samccone** [comment]
xref #1873

**Comment by clintwood** [comment]
@ebidel, @samccone, I needed to solve this now, so based off of your jsbin above I have a hacky workaround here: http://jsbin.com/xemuxe/edit?html,output that solves the specificity issue for now.

Essentially:
```html
<template>
<style>
:host {
  background: var(--foo, red);
  /* specificity - hack */
  --zap-styles: {
    background: orange;
  }
}
:host(.zap) {
  /* specificity - hack */
  @apply(--zap-styles);
}
</style>
<content></content>
</template>
```

**Comment by azogheb** [comment]
:+1: on resolving this issue. Much like @clintwood we have used a workaround by using dummy / no-op var() on the rule that should have more specificity. 

I guess the question is why does Polymer split the CSS into two <style> blocks, one for rules with vars in the first one and one for rules with vars in the second?

**Comment by nazar-pc** [comment]
I'm working on this issue. Got it kind of working, but some tests are failing, so I'll make PR when fix them and add new tests on top.

**Comment by clintwood** [comment]
@nazar-pc, awesome - much needed!

**Comment by nazar-pc** [comment]
Done in #2642, give it a try:)
@ebidel, no one is assigned to this issue, whom should we ask for PR review?

**Comment by TimvdLippe** [comment]
This issues was fixed in #2642 but not closed.

**Comment by samccone** [comment]
Seems like this is still an issue in 1.2.4

http://jsbin.com/suhaqezoqa/edit?html,output

**Comment by cdata** [comment]
I think this may be fixed in master now. Here is a test case: http://output.jsbin.com/caliha

**Comment by nazar-pc** [comment]
Fix was reverted just before release and improved fix landed in master recently.

**Comment by azakus** [comment]
Closing, bug is fixed
