### ISSUE TITLE
<property>-change events are not always fired in Polymer 1.2.2/1.2.3

### ISSUE THREAD

**Issue by neolequang** [Polymer/polymer#2815]
Hi,

I don't know if it's a bug or a new (desired) behavior, but something has changed in `<property>-changed` events in Polymer 1.2.2

I have a custom element element that is a composition of several child custom elements.

Child elements are interested in changes of the value of a property from the parent element.

So I used something similar to what was suggested in issue #2224, and when children are attached, they add an event listener to the parent for the `<property>-changed` event on the parent.

Using this element looks like the following :

```

<host-element>
   <x-parent prop="{{hostProperty}}">
      <x-child></x-child>
      <x-child></x-child>
      ...
   </x-parent>
<host-element>
```

Parent's registration code looks like :
```
    Polymer({
      is: 'x-parent',
      properties: {
        prop: {
          type: Number,
          notify: true,
        }
      },
      ...
```

When I change the `prop` property from the parent, with some code like 
```
this.prop = xxxx;
```
the `prop-changed` event is fired.

But if I change the value by changing the `hostProperty` that is bound to `prop`, then no event is fired. It was fired in Polymer 1.2.1.

I've created a jsbin to reproduce the issue. To see the difference, you will need to switch between 1.2.1 and 1.2.2 in polymer import href.

http://jsbin.com/rupatacuxo/edit?html,console,output

**Comment by beaudesigns** [comment]
:+1: 

We have a similar issue where we're adding a custom event listener for `<property>-changed` events on certain property types. The event listener gets fired the very first time, but not any subsequent times. Digging into it, it looks like the new `_useCache` property in `_notifyChange()` is the culprit.

Manually setting `_useCache` to `false` in our build of Polymer seems to correct the listener.

**Comment by wburgers** [comment]
Adding comment to receive notifications...

I have a child-to-host one-way binding, but I'm not seeing a <property>-changed event (on the host).
Also reflecting back to attribute doesn't seem to work, which is probably based on the same functionality.

**Comment by wburgers** [comment]
Ah never mind my previous comment.
It can be regarded as not sent.
I bound two properties of sibling elements together, one child-to-host and one host-to-child, such that the data would flow from one child to the other via the host.
on the receiving element, I set an attribute ```blaStatus="[[wsStatus]]"```.
This was transferred to the blastatus property on the element, not the blaStatus property.
(Notice the case).
That is why I was not seeing updates.

I did manage to catch the change event eventually.
I added the listener to the wrong object...
The event is only fired on the element itself (in my example below, that would be child1-element.addEventListener(...);
So I thought this was related to this issue, but it was not!

Still weird that the casing is not preserved.

Complete example:
```
<template is="dom-bind" id="demo">
    <child1-element status="{{wsStatus}}"></child1-element> //child-to-host (readOnly & notify inside)
    <child2-element blaStatus="[[wsStatus]]"></child2-element> //host-to-child
</template>
```
child2-element now has a property blastatus instead of the expected blaStatus.

**Comment by MeTaNoV** [comment]
@wburgers 
> Attribute names are converted to lowercase property names. For example, the attribute firstName maps to firstname.
https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping

**Comment by wburgers** [comment]
@MeTaNoV 
I have been using Polymer for quite some time now and still learn new stuff :+1: 
Just a case of RTFM then :wink:
Thanks very much for the info! I really appreciate it.

**Comment by MeTaNoV** [comment]
@wburgers No problem! I am also learning new stuff about our beloved Polymer everyday day! :D I keep reading the doc to be sure not to miss any points but that's a huge tasks! On top of that, trying to follow all issues report... ;) And more...

**Comment by nazar-pc** [comment]
Similar case here, basically example is as following: http://jsbin.com/gudomudaja/edit?html,output
There are 2 textareas, their content is synchronized correctly, but there is no event on opposite side about this:(

**Comment by ebidel** [comment]
@kevinpschaaf @sorvell @sjmiles

**Comment by adamvresky** [comment]
Do you have any new informations about this?

**Comment by ebidel** [comment]
@sorvell said https://github.com/Polymer/polymer/issues/3077 fixes this issue. We're working on a 1.2.4 release very soon that will address this issue.

**Comment by ebidel** [comment]
This should be fixed with 1.2.4, which is now out. Holler if you see otherwise.

**Comment by beaudesigns** [comment]
Unfortunately, I'm still seeing the issue in my scenario, modifying polymer and setting `_useCache: false` still fixes it.

The example that @nazar-pc posted still produces the problem as well.

**Comment by arthurevans** [comment]
@beaudesigns Can you post a jsbin or something reproducing your issue? You may be seeing an unrelated problem.

**Comment by adamvresky** [comment]
Working for me.

**Comment by beaudesigns** [comment]
@arthurevans I am working on replicating how it's being used, here's what I have so far:

https://gist.github.com/beaudesigns/5c155637c3cb6bc54b47

However, it's currently working how I would expect it to. I receive both the `behavior` and `original` log outputs, even with version 1.2.3. However, on our production environment (and code), I only see the `original` log output.

I'm digging into it now to see if there's something else creating an issue. Thanks for your patience.

**Comment by beaudesigns** [comment]
I found it! https://gist.github.com/beaudesigns/5c155637c3cb6bc54b47

This first change to the input will show both the `behavior` and `original` `console.log`. Subsequent changes will only show the `original` `console.log`.

What causes this, is on the behavior `-changed` event, I was doing an `event.stopPropagation()`. Because it uses the cache, I'm assuming it sets `bubbles: false`.

If this is intended, I can rework my code, I believe the `stopPropagation` was put in there as a safety measure, and may not be required anymore.

**Comment by sorvell** [comment]
Data events are re-used as a performance optimization. Since they do not bubble by design, there's no reason to call `stopPropagation`. Doing so impairs their ability to be re-used so I recommend simply removing that line.

**Comment by beaudesigns** [comment]
Yes, I've removed it and everything appears to be working normally. Thanks for straightening me out on that.
