### ISSUE TITLE
Errors in 2.0 child element templating

### ISSUE THREAD

**Issue by caranicas** [Polymer/polymer#4098]
### Description

I've run into 2 different errors and some strange behavior when extending classes in polymer 2.0. The issues arise when my child element has a template that excludes some or all of the properties that are displayed in the parent's template. 
#### Live Demo

These need to opened in Canary for the customElements.define to work. 

This first example is a baseline with no errors. Demonstrating a child that inherits values from a parent, overwrites one, and adds it's own, and then displays all 3 in its template.  
- [properly working](http://jsbin.com/padebopopo/1/edit?html,output)

This next demo also demonstrates a desired result. It is the same two classes, but now the child doesn't have `prop2` in it's template
- [properly working](http://jsbin.com/qixetusale/1/edit?html,output)

This is where strange stuff happens. When I remove `prop2` from the `ChildEl` properties then the `child-el` template gets the parents `prop2` value where the `prop3` value should be displayed. 
- [incorrect props](http://jsbin.com/hutapejuha/edit?html,output)

The next example demonstrates the error you get when your child template doesn't use any of the properties defined in the parent's template, but does try to display its own properties.
- [Cannot read property '__dataCompoundStorage' of undefined](http://jsbin.com/vuwahewena/edit?html,console,output)

The example demonstrates the error when your child template doesn't use any of the properties in the parent template, or any of its own properties. 
- [Cannot read property '0' of null](http://jsbin.com/fuvamaqeye/1/edit?html,console,output)
### Browsers Affected
- [X] Chrome Canary
### Versions

2.0-preview

**Comment by sorvell** [comment]
Thanks for the detailed report. The issue is that property effects that come from the template (what we call "propagateEffects") are not properly being reset for subclasses. The [offending line here](https://github.com/Polymer/polymer/blob/2.0-preview/src/elements/element.html#L157) looks like it broke when we changed `_propagateEffects` to `__propagateEffects`. 

@kevinpschaaf can we go ahead and move the resetting of propagation effects into `_bindTemplate` so we can avoid this kind of brittleness in the future?

**Comment by kevinpschaaf** [comment]
Will be resolved in #4106.

jsBins using PR branch demonstrating fix:

* [Incorrect props](http://jsbin.com/vozali/edit?html,output)
* [Cannot read property '0' of null](http://jsbin.com/mayesoy/edit?html,console,output)

**Comment by kevinpschaaf** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4106

**Comment by Saulis** [comment]
Hi!

The "Cannot read property 'x' of null" issue still exists in case two-way binding is used in the base template.

Please see: http://jsbin.com/doqaras/edit?html,console,output

**Comment by Saulis** [comment]
ping @kevinpschaaf

**Comment by kevinpschaaf** [comment]
Re-opening, looks like `_bindListeners` also needs to get reset in `bindTemplate`.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4331.
