### ISSUE TITLE
Polymer 1.9 resolveUrl does not work as intended

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4532]
### Description

`this.resolveUrl` in a properties block is simply just not working as intended.

#### Live Demo

Wrong: http://jsbin.com/ridukodefe/2/edit?html,console
Intended: https://jsbin.com/sekeyeheso/1/edit?html,console

#### Steps to Reproduce

1. Create element
2. Add a property in the properties block
3. set `value: function() { return this.resolveUrl('./relativeUrlThatExists')}`
4. set the url of `resolveUrl` to something that exists.
5. observe that it does not find the proper url

#### Expected Results

it should return the actual absolute url

#### Actual Results

it just returns the same relative url entered

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.9.0
- webcomponents: v0

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/pull/4533.

**Comment by daniele-orlando** [comment]
I can still reproduce this bug on Polymer 1.9.3 and Polymer-Cli 1.5.2 under Vulcanize.

```js
this.resolveUrl('../my-lib/element.html')
// => ../my-lib/element.html
```
